kind: pipeline
type: docker
name: default


steps:
  - name: fix-permissions
    image: alpine
    user: root
    commands:
    - chmod -R 0777 /drone/src
    depends_on:
      - clone
  - name: Build Editor
    image: ghcr.io/epicgames/unreal-engine:dev-slim-5.3.2
    commands:
      - cd engine
      - pip3 install ue4cli
      - export PATH="/home/ue4/.local/bin:$PATH"
      - bash Build/ContinuousIntegration/build_project.sh
      - echo "The commit builds"
    depends_on:
      - fix-permissions

  - name: Package Project
    image: ghcr.io/epicgames/unreal-engine:dev-slim-5.3.2
    commands:
      - cd engine
      - pip3 install ue4cli
      - export PATH="/home/ue4/.local/bin:$PATH"
      - bash Build/ContinuousIntegration/package_ue5_project.sh "TestWorlds" ${DRONE_COMMIT:0:7}
      - echo "The pull request was successfully packaged"
    depends_on:
      - Build Editor

  ## Pushes build to minio, after which the python, or client, side can pull the binaries from there
  - name: Push to S3
    image: plugins/s3
    settings:
      bucket: holo
      access_key:
        from_secret: minio_username
      secret_key:
        from_secret: minio_password
      source: engine/final/*
      strip_prefix: engine/final/
      target: /TestWorlds/${DRONE_BRANCH}
      path_style: true
      # endpoint: http://minio:9000/
      endpoint: http://robots.et.byu.edu:9000
    depends_on:
      - Package Project

  - name: Push Tagged S3
    image: plugins/s3
    settings:
      bucket: holo
      access_key:
        from_secret: minio_username
      secret_key:
        from_secret: minio_password
      source: engine/final/*
      strip_prefix: engine/final/
      target: /TestWorlds/${DRONE_TAG}
      path_style: true
      # endpoint: http://minio:9000/
      endpoint: http://robots.et.byu.edu:9000
    when:
      event:
        - tag
    depends_on:
      - Package Project

  - name: Push Tagged S3 2
    image: plugins/s3
    settings:
      bucket: holo
      access_key:
        from_secret: minio_username
      secret_key:
        from_secret: minio_password
      source: engine/tag/*
      strip_prefix: engine/tag/
      target: /TestWorlds/${DRONE_TAG}
      path_style: true
      # endpoint: http://minio:9000/
      endpoint: http://robots.et.byu.edu:9000
    when:
      event:
        - tag
    depends_on:
      - Package Project

  ## Build a temporary docker image that contains everything necessary to simplify further steps
  - name: build_docker
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - |
        cd client
        if [ "$DRONE_BUILD_EVENT" = "pull_request" ] && \
          ( [ "$DRONE_BRANCH" = "release" ] || [ "$DRONE_BRANCH" = "develop" ] ); then
          REPO_NAME2="pr-${DRONE_COMMIT:0:7}"
        else
          REPO_NAME2="${DRONE_COMMIT:0:7}"
        fi

        echo "Repo name is: $REPO_NAME2"
        docker build -t "byu-holoocean/holoocean:$REPO_NAME2" .
        echo "$REPO_NAME2" > ../.tag
    depends_on:
      - Push to S3
  
  - name: install_package
    image: "byu-holoocean/holoocean:${DRONE_COMMIT:0:7}"
    environment:
      HOLODECKPATH: packages
    commands:
      - cd client
      - pip3 install .
      - python3 -c "import holoocean; holoocean.install('TestWorlds', branch='${DRONE_BRANCH}', commit='${DRONE_COMMIT:0:7}')"
    depends_on:
      - build_docker
    when:
      event:
       exclude:
        - pull_request
        - tag

  - name: install_package_tag
    image: "byu-holoocean/holoocean:${DRONE_COMMIT:0:7}"
    environment:
      HOLODECKPATH: packages
    commands:
      - cd client
      - pip3 install .
      - python3 -c "import holoocean; holoocean.install('TestWorlds', branch='${DRONE_TAG}', commit='${DRONE_COMMIT:0:7}')"
    depends_on:
      - build_docker
    when:
      event:
      - tag

  - name: install_package_pr
    image: "byu-holoocean/holoocean:pr-${DRONE_COMMIT:0:7}"
    environment:
      HOLODECKPATH: packages
    commands:
      - cd client
      - pip3 install .
      - python3 -c "import holoocean; holoocean.install('TestWorlds', branch='${DRONE_BRANCH}', commit='${DRONE_COMMIT:0:7}')"
    depends_on:
      - build_docker
    when:
      event:
        - pull_request
  

  ## Run through all python tests

  # Test Python 3.9
  - name: py39-agents
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py39-agents"
    depends_on:
      - install_package
      - install_package_pr
      - install_package_tag
    when:
      branch:
        - release
        - develop
   
  - name: py39-lcm
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py39-lcm"
    depends_on:
      - py39-agents
    when:
      branch:
        - release
        - develop

  - name: py39-scenarios
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py39-scenarios"
    depends_on:
      - py39-lcm
    when:
      branch:
        - release
        - develop

  # Test Python 3.10
  - name: py310-agents
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py310-agents"
    depends_on:
      - install_package
      - install_package_pr
    when:
      branch:
        - release
        - develop

  - name: py310-lcm
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py310-lcm"
    depends_on:
      - py310-agents
    when:
      branch:
        - release
        - develop

  - name: py310-scenarios
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py310-scenarios"
    depends_on:
      - py310-lcm
    when:
      branch:
        - release
        - develop

  # Test Python 3.11
  - name: py311-agents
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py311-agents"
    depends_on:
      - install_package
      - py39-scenarios
    when:
      branch:
        - release
        - develop

  - name: py311-lcm
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py311-lcm"
    depends_on:
      - py311-agents
    when:
      branch:
        - release
        - develop

  - name: py311-scenarios
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py311-scenarios"
    depends_on:
      - py311-lcm
    when:
      branch:
        - release
        - develop

  # Test Python 3.12
  - name: py312-agents
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py312-agents"
    depends_on:
      - install_package
      - py310-scenarios
    when:
      branch:
        - release
        - develop

  - name: py312-lcm
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py312-lcm"
    depends_on:
      - py312-agents
    when:
      branch:
        - release
        - develop

  - name: py312-scenarios
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py312-scenarios"
    depends_on:
      - py312-lcm
    when:
      branch:
        - release
        - develop

  # Test Python 3.13
  - name: py313-agents
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py313-agents"
    depends_on:
       - install_package
       - py311-scenarios

  - name: py313-lcm
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - echo $$CONTAINER
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py313-lcm"
    depends_on:
      - py313-agents

  - name: py313-scenarios
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py313-scenarios"
    depends_on:
      - py313-lcm
      
  ## Test Python 3.9-3.13 Sensors

  - name: py39-sensors
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py39-sensors"
    depends_on:
      - py39-scenarios
      - py310-scenarios
      - py311-scenarios
      - py312-scenarios
      - py313-scenarios
    when:
      branch:
        - release
        - develop

  - name: py310-sensors
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py310-sensors"
    depends_on:
      - py39-sensors
    when:
      branch:
        - release
        - develop

  - name: py311-sensors
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py311-sensors"
    depends_on:
      - py310-sensors
    when:
      branch:
        - release
        - develop

  - name: py312-sensors
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py312-sensors"
    depends_on:
      - py311-sensors
    when:
      branch:
        - release
        - develop

  - name: py313-sensors
    image: docker:24.0-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - export CONTAINER=$$(hostname)
      - docker run --rm --gpus all --volumes-from $CONTAINER "byu-holoocean/holoocean:$(cat /drone/src/.tag)" sh -c "cd /drone/src/client && tox -e py313-sensors"
    depends_on:
      - py313-scenarios
      - py312-sensors

  - name: Update_Docs_repo 
    image: "byu-holoocean/holoocean:${DRONE_COMMIT:0:7}"
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - git clone https://github.com/byu-holoocean/holoocean-docs.git
      - pip3 install bs4 sphinx==5.0.2 sphinx-rtd-theme==2.0.0 sphinx-copybutton==0.5.2 autodocsumm==0.2.12 scipy
      - export PATH="/home/ue4/.local/bin:$PATH"
      - python3 client/docmaker.py
      - cd holoocean-docs
      - python3 new_version.py ${DRONE_TAG}
      - cd ..
      - mv docs holoocean-docs/${DRONE_TAG}
      - cd holoocean-docs
      - python3 Sidebar_version_links.py ${DRONE_TAG}
      - git add .
      # - git commit -m "Update to version ${DRONE_TAG}"
      # - git reset --soft HEAD~2
      - git commit -m "Update to version ${DRONE_TAG}"
      - git push -f
    depends_on:
      - build_docker
    when:
      event:
        - tag

  - name: Update_Docs_repo_develop
    image: "byu-holoocean/holoocean:${DRONE_COMMIT:0:7}"
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - git clone https://github.com/byu-holoocean/holoocean-docs.git
      - pip3 install bs4 sphinx==5.0.2 sphinx-rtd-theme==2.0.0 sphinx-copybutton==0.5.2 autodocsumm==0.2.12 scipy
      - export PATH="/home/ue4/.local/bin:$PATH"
      - python3 client/docmaker.py
      - rm -rf holoocean-docs/develop
      - mv docs holoocean-docs/develop
      - cd holoocean-docs
      - python3 Sidebar_version_links.py develop
      - git add .
      # - git commit -m "Update to develop"
      # - git reset --soft HEAD~2
      - git commit --allow-empty -m "${DRONE_COMMIT_MESSAGE//\"/\\\""}"
      - git push -f
    depends_on:
      - build_docker
    when:
      branch:
        - develop
      event:
        exclude:
        - pull_request

  ## Clean up docker image off of the server
  - name: remove-docker-image
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
     - docker rmi -f "byu-holoocean/holoocean:$(cat /drone/src/.tag)"
     - docker volume prune -f -a

    depends_on:
     - py313-sensors
    when:
      status:
        - success
        - failure

  ## Message slack on success/fail
  - name: notify-slack
    image: plugins/slack-blame
    environment:
    settings:
      token:
        from_secret: slack_token
      channel: holoocean_builds
      success_template: |
        SUCCESS! Build #{{build.number}} passed for {{repo.name}}: {{build.message}} on {{build.branch}}!
      failure_template: |
        FAILURE! Build #{{build.number}} failed on steps {{DRONE_FAILED_STEPS}} for {{repo.name}}: {{build.message}} on {{build.branch}}!
    depends_on:
      - remove-docker-image
    
    when:
      status:
        - success
        - failure

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

